import { Event } from './types';

// Sample events for development and testing
export const sampleEvents: Event[] = [
  {
    id: '1',
    title: 'Beechworth Farmers Market',
    description: 'The monthly Beechworth Farmers Market features local produce, artisan goods, fresh baked treats, and live music. Meet local farmers and producers while enjoying the historic town center atmosphere.',
    image_url: 'https://images.unsplash.com/photo-1488459716781-31db52582fe9?w=800&h=600&fit=crop',
    start_date: new Date(Date.now() + 2 * 24 * 60 * 60 * 1000).toISOString(),
    end_date: null,
    location: 'Ford Street, Beechworth VIC 3747',
    venue_name: 'Beechworth Town Center',
    category: 'market',
    ticket_url: null,
    is_free: true,
    price: null,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '2',
    title: 'Jazz in the Vines',
    description: 'An evening of smooth jazz surrounded by the beautiful vineyards of the Beechworth wine region. Local and interstate jazz musicians perform under the stars. BYO picnic or purchase from local food vendors.',
    image_url: 'https://images.unsplash.com/photo-1514525253161-7a46d19cd819?w=800&h=600&fit=crop',
    start_date: new Date(Date.now() + 5 * 24 * 60 * 60 * 1000).toISOString(),
    end_date: null,
    location: 'Pennyweight Winery, Beechworth VIC',
    venue_name: 'Pennyweight Winery',
    category: 'music',
    ticket_url: 'https://example.com/tickets',
    is_free: false,
    price: '$45 per person',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '3',
    title: 'Historic Gold Mine Tour',
    description: 'Explore the rich gold mining history of Beechworth with a guided tour of the old gold mines. Learn about the Chinese miners, the eureka stockade, and the impact of the gold rush on the region.',
    image_url: 'https://images.unsplash.com/photo-1518709766631-a6a7f45921c3?w=800&h=600&fit=crop',
    start_date: new Date(Date.now() + 1 * 24 * 60 * 60 * 1000).toISOString(),
    end_date: null,
    location: 'Historic Precinct, Beechworth VIC',
    venue_name: 'Burke Museum',
    category: 'community',
    ticket_url: null,
    is_free: false,
    price: '$20 adults / $10 kids',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '4',
    title: 'Community Yoga in the Park',
    description: 'Start your Sunday morning with a relaxing yoga session in the beautiful Lake Sambell park. All levels welcome. Bring your own mat and water bottle.',
    image_url: 'https://images.unsplash.com/photo-1544367567-0f2fcb009e0b?w=800&h=600&fit=crop',
    start_date: new Date(Date.now() + 3 * 24 * 60 * 60 * 1000).toISOString(),
    end_date: null,
    location: 'Lake Sambell, Beechworth VIC',
    venue_name: 'Lake Sambell Park',
    category: 'sport',
    ticket_url: null,
    is_free: true,
    price: null,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '5',
    title: 'Beechworth Bakery Masterclass',
    description: 'Learn the secrets of the famous Beechworth Bakery! Join our bakers for a hands-on bread making workshop. Take home your creations and a recipe booklet.',
    image_url: 'https://images.unsplash.com/photo-1509440159596-0249088772ff?w=800&h=600&fit=crop',
    start_date: new Date(Date.now() + 7 * 24 * 60 * 60 * 1000).toISOString(),
    end_date: null,
    location: '27 Camp St, Beechworth VIC 3747',
    venue_name: 'Beechworth Bakery',
    category: 'workshop',
    ticket_url: 'https://example.com/bakery',
    is_free: false,
    price: '$85 per person',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '6',
    title: 'Ned Kelly Historical Walk',
    description: 'Walk through the historic streets of Beechworth and visit the sites associated with the famous bushranger Ned Kelly. See the courthouse where he was tried and the gaol where he was held.',
    image_url: 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800&h=600&fit=crop',
    start_date: new Date(Date.now() + 4 * 24 * 60 * 60 * 1000).toISOString(),
    end_date: null,
    location: 'Beechworth Historic Precinct',
    venue_name: 'Beechworth Visitor Centre',
    category: 'community',
    ticket_url: null,
    is_free: true,
    price: null,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '7',
    title: 'Local Art Exhibition Opening',
    description: 'Celebrate the opening of a new exhibition featuring works by local Beechworth and North East Victorian artists. Wine and cheese provided. Artists will be present to discuss their work.',
    image_url: 'https://images.unsplash.com/photo-1531243269054-5ebf6f34081e?w=800&h=600&fit=crop',
    start_date: new Date(Date.now() + 6 * 24 * 60 * 60 * 1000).toISOString(),
    end_date: null,
    location: 'Gallery 101, Beechworth VIC',
    venue_name: 'Beechworth Art Gallery',
    category: 'art',
    ticket_url: null,
    is_free: true,
    price: null,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '8',
    title: 'Golden Horseshoes Festival',
    description: 'Annual celebration of Beechworth\'s gold mining heritage with live entertainment, historical reenactments, food stalls, and activities for the whole family. Don\'t miss the gold panning competition!',
    image_url: 'https://images.unsplash.com/photo-1533174072545-7a4b6ad7a6c3?w=800&h=600&fit=crop',
    start_date: new Date(Date.now() + 14 * 24 * 60 * 60 * 1000).toISOString(),
    end_date: new Date(Date.now() + 16 * 24 * 60 * 60 * 1000).toISOString(),
    location: 'Beechworth Town Center',
    venue_name: 'Various Locations',
    category: 'festival',
    ticket_url: 'https://example.com/festival',
    is_free: false,
    price: '$15 day pass',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
];
